### ISSUE TITLE
Use property-based testing tool to check your specifications.

### ISSUE THREAD

**Issue by jbgi** [NCR-CoDE/JavaForSmallTeams#16]
Testing section should mention property-based testing: a lot better than to manually pick a few example. Hand picked examples are only good for non-regression tests.

**Comment by hcoles** [comment]
I've added an [update](https://github.com/NCR-CoDE/JavaForSmallTeams/commit/7471f01113bd5b68c945a64105b94dcfd677522d) that briefly mentions property based testing.

While it's something I personally find quite interesting, there isn't much experience of it in the Java community on commercial codebases. The only mature framework I'm aware of that has seen substantial use is ScalaCheck, which has mainly be used with scala.

I don't want to cover it in any detail until there is more real world experience to draw on of using it in Java.

**Comment by jbgi** [comment]
yes. fair enough.
