### ISSUE TITLE
Existing date/time dependency - Java 8 Clock

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [NCR-CoDE/JavaForSmallTeams#4]
Regarding unit testing and date/time
https://ncrcoe.gitbooks.io/java-for-small-teams/content/tests/2300_testing_FAQS.html

There's a new class [java.time.Clock](https://docs.oracle.com/javase/8/docs/api/java/time/Clock.html) available for this in Java 8.
With static methods `systemDefaultZone()` for production and fixed() to get a `fixed()` time for unit tests.

Joda Time has [MillisProvider](http://www.joda.org/joda-time/apidocs/org/joda/time/DateTimeUtils.MillisProvider.html). Unfortunately it's only an interface so one has to implement a production implementation for the current time oneself.

**Comment by hcoles** [comment]
Thanks - Clock is definitely worth mentioning.

As the purpose of MillisProvider seems to be update some static state within joda time I think it is probably better not to point people towards it. An explicit dependency on a strategy that provides the current time would be better.

**Comment by hcoles** [comment]
@arend-von-reinersdorff Is there anything you'd like to add on this or should I close the issue?

**Comment by arend-von-reinersdorff** [comment]
Very nice - thanks for the update :-)
