### ISSUE TITLE
Prefer immutable objects / Know how to implement hashcode and equals

### ISSUE THREAD

**Issue by jbgi** [NCR-CoDE/JavaForSmallTeams#7]
Those sections do not mention than writing immutable class (with associated hashcode/equals) by your-self is a thing of the past for most use cases.
You should use a compile-time annotation processor for this task: much less error-prone & many features out-of-the-box that you don't have to write yourself (ie. functional setter).
I can recommend 4 annotation processors for this task:
- https://github.com/google/auto/tree/master/value
- http://immutables.github.io/
- https://github.com/sviperll/adt4j/
- https://github.com/derive4j/derive4j
  (this last one I wrote)

**Comment by hcoles** [comment]
Implementing hashcode and equals by hand is not "a thing of the past". Code generators have both advantages and disadvantages that need to be considered.

I've added some content around this on the branch here for discussion

https://github.com/NCR-CoDE/JavaForSmallTeams/commit/642240e8e4645c08390bd16f1549689eea5c7290
