### ISSUE TITLE
For small teams?

### ISSUE THREAD

**Issue by magJ** [NCR-CoDE/JavaForSmallTeams#8]
Hi, love the book.

However I am wondering what sections of advice in particular only apply to "small" teams?
Reading through the book I haven’t really noticed anything in particular that would be a bad idea or wouldn’t apply to a large team.
If anything I think many of the items discussed become more important the larger the team size.
I think the books name might dissuade readers from large teams from approaching it, while they could still stand to gain quite a lot from reading it.

**Comment by hcoles** [comment]
If you have a large organisation where developers have been organised into small teams then the advice should all apply.

If you have a large organisation where things have been split by job function or some other scheme that generates large teams trying to work on the same code then I think a lot of the advice will apply. But not all of it.

I've not seen large teams like this working well anywhere, but I think you'd have more success with a more conservative and prescriptive set of guidelines. Basically the you'd need to cater for a lower common denominator.

**Comment by magJ** [comment]
Thanks.
